name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # - name: Mal schauen
      #   run: |
      #     echo "Hallo"
      #     ls

      - name: Checkout
        uses: actions/checkout@v4

      - name: Anschauen
        run: |
          ls
      
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1) Schritt, der "npm clean-install" ausführt, um die Abhängigkeiten zu installieren
      - name: Install Dependencies
        run: |
          npm clean-install

      # 2) Schritt, der "npm run build" ausführt, um die Website zu erstellen
      - name: Run the npm build
        run: |
          npm run build

      # 3) Schritt, der mit "ls -R dist/" die erzeugten Dateien auflistet
      - name: Lookup results in directory dist/
        run: |
          ls -R dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: dist
          retention-days: 3 # default: 3

  deploy:
    runs-on: ubuntu-latest
    # requires completed build
    needs:
      - build
    steps:
    # requires cloud credentials for the cloud to deploy to (AWS S3 bucket)
    # login to web server
    # copy build artifact to the web server

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: dist

      - name: Lookup results in directories . and dist/
        run: |
          ls
          echo "-------------------"
          ls -R dist/

      - name: Lookup Configured Credentials
        run: |
          echo "${{ vars.BUCKET_NAME }}"
          echo "${{ SECRETS.AWS_ACCESS_KEY_ID }}"
          echo "${{ SECRETS.AWS_SECRET_ACCESS_KEY }}"

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: "${{ SECRETS.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key:  "${{ SECRETS.AWS_SECRET_ACCESS_KEY }}"
          aws-region: eu-central-1
